export default {
  height: 200,
  buttonList: [
    [
      "undo",
      "redo",
      "font",
      "fontSize",
      "formatBlock",
      "paragraphStyle",
      "blockquote",
      "bold",
      "underline",
      "italic",
      "strike",
      "subscript",
      "superscript",
      "fontColor",
      "hiliteColor",
      "removeFormat",
      "outdent",
      "indent",
      "align",
      "horizontalRule",
      "list",
      "lineHeight",
      "table",
      "fullScreen",
      "showBlocks",
      "codeView",
      "preview",
    ],
  ],
  colorList: [
    [
      "#ccc",
      "#dedede",
      "#000",
      "OrangeRed",
      "Orange",
      "RoyalBlue",
      "SaddleBrown",
    ],
    ["SlateGray", "BurlyWood", "DeepPink", "FireBrick", "Gold", "SeaGreen"],
  ],
  fontSize: [8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72],
};
